# Generated by Django 4.2 on 2026-02-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分组名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分组',
                'verbose_name_plural': '分组',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='知识点名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
                'db_table': 'knowledge_points',
            },
        ),
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='题目标题')),
                ('content', models.TextField(verbose_name='题干内容')),
                ('solution', models.TextField(blank=True, verbose_name='解题过程')),
                ('correct_answer', models.TextField(blank=True, verbose_name='正确答案')),
                ('user_answer', models.TextField(blank=True, verbose_name='用户答案')),
                ('analysis', models.TextField(blank=True, verbose_name='错因分析')),
                ('error_cause', models.CharField(choices=[('knowledge', '知识性错误'), ('logic', '逻辑性错误'), ('habit', '习惯性错误'), ('custom', '自定义')], default='knowledge', max_length=20, verbose_name='错因类型')),
                ('custom_error_cause', models.CharField(blank=True, max_length=100, verbose_name='自定义错因')),
                ('difficulty', models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=2, verbose_name='难度')),
                ('mastery_level', models.CharField(choices=[('to_review', '待复习'), ('mastered', '已掌握')], default='to_review', max_length=20, verbose_name='掌握程度')),
                ('review_count', models.IntegerField(default=0, verbose_name='复习次数')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后复习时间')),
                ('next_review_at', models.DateTimeField(blank=True, null=True, verbose_name='下次复习时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '错题',
                'verbose_name_plural': '错题',
                'db_table': 'mistakes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MistakeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mistake_images/', verbose_name='图片')),
                ('ocr_text', models.TextField(blank=True, verbose_name='OCR识别文字')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '错题图片',
                'verbose_name_plural': '错题图片',
                'db_table': 'mistake_images',
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('mastered', '已掌握'), ('wrong_again', '再次错误')], max_length=20, verbose_name='复习结果')),
                ('notes', models.TextField(blank=True, verbose_name='复习笔记')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='复习时间')),
            ],
            options={
                'verbose_name': '复习记录',
                'verbose_name_plural': '复习记录',
                'db_table': 'review_records',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学科名称')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='主题颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学科',
                'verbose_name_plural': '学科',
                'db_table': 'subjects',
            },
        ),
    ]
