# Generated by Django 4.2 on 2026-02-14 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mistakes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='reviewrecord',
            name='mistake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='mistakes.mistake', verbose_name='所属错题'),
        ),
        migrations.AddField(
            model_name='mistakeimage',
            name='mistake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mistakes.mistake', verbose_name='所属错题'),
        ),
        migrations.AddField(
            model_name='mistake',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistakes', to='mistakes.group', verbose_name='所属分组'),
        ),
        migrations.AddField(
            model_name='mistake',
            name='knowledge_points',
            field=models.ManyToManyField(blank=True, related_name='mistakes', to='mistakes.knowledgepoint', verbose_name='知识点'),
        ),
        migrations.AddField(
            model_name='mistake',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='mistakes.subject', verbose_name='所属学科'),
        ),
        migrations.AddField(
            model_name='mistake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='knowledgepoint',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_points', to='mistakes.subject', verbose_name='所属学科'),
        ),
        migrations.AddField(
            model_name='knowledgepoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_points', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mistakes.group', verbose_name='父分组'),
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='mistakes.subject', verbose_name='所属学科'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_groups', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='knowledgepoint',
            unique_together={('user', 'subject', 'name')},
        ),
    ]
