# Generated by Django 4.2 on 2026-02-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistakes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['order', 'created_at'], 'verbose_name': '学科', 'verbose_name_plural': '学科'},
        ),
        migrations.AddField(
            model_name='subject',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
