# Generated by Django 4.2 on 2026-02-18 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mistakes', '0003_alter_subject_options_subject_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review_images/', verbose_name='图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('review_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mistakes.reviewrecord', verbose_name='所属复习记录')),
            ],
            options={
                'verbose_name': '复习图片',
                'verbose_name_plural': '复习图片',
                'db_table': 'review_images',
            },
        ),
    ]
