# Generated by Django 4.2 on 2026-02-18 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mistakes', '0004_reviewimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='积分变动')),
                ('reason', models.CharField(choices=[('review', '复习题目'), ('on_time_review', '按时复习'), ('early_review', '提前复习'), ('difficulty_bonus', '难度奖励')], max_length=20, verbose_name='变动原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mistake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_records', to='mistakes.mistake', verbose_name='相关错题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分记录',
                'verbose_name_plural': '积分记录',
                'db_table': 'points_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
