# Generated by Django 4.2 on 2026-03-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistakes', '0005_pointsrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistake',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='题目标题'),
        ),
    ]
