# Generated by Django 4.2 on 2026-03-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistakes', '0006_alter_mistake_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistakeimage',
            name='image_type',
            field=models.CharField(choices=[('content', '题干图片'), ('solution', '解题过程图片'), ('correct_answer', '正确答案图片'), ('user_answer', '我的答案图片')], default='content', max_length=20, verbose_name='图片类型'),
        ),
    ]
