# Generated by Django 4.2 on 2026-02-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_review_limit',
            field=models.IntegerField(default=10, verbose_name='每日复习题目数量'),
        ),
    ]
