# Generated by Django 4.2 on 2026-02-14 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aihelper', '0002_initial'),
        ('mistakes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socraticsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socratic_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='socraticmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='aihelper.socraticsession', verbose_name='所属会话'),
        ),
        migrations.AddField(
            model_name='similarproblem',
            name='original_mistake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_problems', to='mistakes.mistake', verbose_name='原错题'),
        ),
        migrations.AddField(
            model_name='similarproblem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_problems', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='reviewplan',
            name='mistake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_plans', to='mistakes.mistake', verbose_name='错题'),
        ),
        migrations.AddField(
            model_name='reviewplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_plans', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
