# Generated by Django 4.2 on 2026-03-01 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aihelper', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimilarProblem',
        ),
    ]
