# Generated by Django 4.2 on 2026-02-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='计划复习日期')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '复习计划',
                'verbose_name_plural': '复习计划',
                'db_table': 'review_plans',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='SimilarProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='题目标题')),
                ('content', models.TextField(verbose_name='题干内容')),
                ('solution', models.TextField(blank=True, verbose_name='解题过程')),
                ('correct_answer', models.TextField(blank=True, verbose_name='正确答案')),
                ('difficulty', models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=2, verbose_name='难度')),
                ('is_practiced', models.BooleanField(default=False, verbose_name='是否已练习')),
                ('practiced_at', models.DateTimeField(blank=True, null=True, verbose_name='练习时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '相似题',
                'verbose_name_plural': '相似题',
                'db_table': 'similar_problems',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocraticMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('ai', 'AI')], max_length=10, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('is_stuck_point', models.BooleanField(default=False, verbose_name='是否是卡点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '苏格拉底消息',
                'verbose_name_plural': '苏格拉底消息',
                'db_table': 'socratic_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocraticSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否进行中')),
            ],
            options={
                'verbose_name': '苏格拉底对话',
                'verbose_name_plural': '苏格拉底对话',
                'db_table': 'socratic_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
