# Generated by Django 4.2 on 2026-02-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aihelper', '0001_initial'),
        ('mistakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socraticsession',
            name='mistake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socratic_sessions', to='mistakes.mistake', verbose_name='所属错题'),
        ),
    ]
